# B

# mtcars veri setini yukleyelim

```{r}
data(mtcars)

my_summary_stats <- function(vector) 
{
  mean = mean(vector, na.rm = TRUE)
  median = median(vector, na.rm = TRUE)
  sd = sd(vector, na.rm = TRUE)
  min = min(vector, na.rm = TRUE)
  max = max(vector, na.rm = TRUE)
  
  returnList <- list(mean, median, sd, min, max)
  return(returnList)
}
```

# Sayisal sütunlar üzerinde döngü ile işlem yapılması

```{r}
# Sayisal sütunlar üzerinde döngü ile işlem yapılması
for (column_name in colnames(mtcars)) {
  if (is.numeric(mtcars[[column_name]])) {
   listem <- my_summary_stats(mtcars[[column_name]])
   cat("Ozet İstatistikler -", column_name, ":\n")
   print(listem)
  }
}
```

# sayısal sütunlar için apply kullanımı

```{r}
apply(mtcars, 2, mean)
apply(mtcars, 2, median)
apply(mtcars, 2, sd)
apply(mtcars, 2, min)
apply(mtcars, 2, max)
```

# C

# dslabs veri setini yukleyelim

```{r}
install.packages("dslabs")
library(dslabs)
data(na_example)
sum(is.na(na_example))

na_example[is.na(na_example)] <- 2025
cleaned_data <- na_example 
print(cleaned_data)
```
